version: '3.8'
services:
  video-streamer:
    network_mode: "host"
    build: ./video-streamer
    volumes:
      - ./videos:/stream

  processing-pipeline:
    build: ./processing-pipeline
    volumes:
      - ./data:/app/data  # Mount a local folder to store output data
    depends_on:
      - video-streamer

volumes:
  data:
